<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-02T16:51:24 IST" name="Suite" finished-at="2024-04-02T16:51:52 IST" duration-ms="27370">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@1623b78d]" name="runScenario" class="io.cucumber.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test started-at="2024-04-02T16:51:24 IST" name="Test" finished-at="2024-04-02T16:51:52 IST" duration-ms="27370">
      <class name="parallel.ParallelRun">
        <test-method is-config="true" signature="setUpClass(org.testng.ITestContext)[pri:0, instance:parallel.ParallelRun@1623b78d]" started-at="2024-04-02T16:51:24 IST" name="setUpClass" finished-at="2024-04-02T16:51:25 IST" duration-ms="1195" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@1c8f6c66]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@1623b78d]" started-at="2024-04-02T16:51:25 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-04-02T16:51:45 IST" duration-ms="19361" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["To check we are not able to login with invalid credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login Functionality"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@1623b78d]" started-at="2024-04-02T16:51:25 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-04-02T16:51:44 IST" duration-ms="18878" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["To check the we are able to login the application with the valid credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login feature"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@1623b78d]" started-at="2024-04-02T16:51:25 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-04-02T16:51:45 IST" duration-ms="19167" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["To check we are not able to login with invalid credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login feature"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at parallel.Login.user_should_be_redirected_to_the_dashboard(Login.java:39)
at ✽.user should be redirected to the dashboard "1Test Automation Practice: Working with Login form"(file:///C:/Users/Hustler/eclipse-workspace/CucumberPOM/src/test/resources/parallel/Login.feature:27)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@1623b78d]" started-at="2024-04-02T16:51:25 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-04-02T16:51:45 IST" duration-ms="20062" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["To check we are not able to login with invalid credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login feature"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@1623b78d]" started-at="2024-04-02T16:51:25 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-04-02T16:51:45 IST" duration-ms="20016" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA["To check we are not able to login with invalid credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login with 3rd invalid credential"]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method signature="runScenario(io.cucumber.testng.PickleWrapper,io.cucumber.testng.FeatureWrapper)[pri:0, instance:parallel.ParallelRun@1623b78d]" started-at="2024-04-02T16:51:25 IST" name="runScenario" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2024-04-02T16:51:44 IST" duration-ms="18927" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA["To check the we are able to login the application with the valid credentials"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Login feature"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at parallel.Login.user_should_be_redirected_to_the_dashboard(Login.java:39)
at ✽.user should be redirected to the dashboard "2Test Automation Practice: Working with Secure Page"(file:///C:/Users/Hustler/eclipse-workspace/CucumberPOM/src/test/resources/parallel/Login.feature:21)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method is-config="true" signature="tearDownClass()[pri:0, instance:parallel.ParallelRun@1623b78d]" started-at="2024-04-02T16:51:45 IST" name="tearDownClass" finished-at="2024-04-02T16:51:52 IST" duration-ms="6035" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- parallel.ParallelRun -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
